[package]
name = "mev-core"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
solana-sdk = "1.17"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
rkyv = { version = "0.7", features = ["validation"] }
bytemuck = { version = "1.14", features = ["derive"] }
